[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "diffractom"
version = "0.1.0"
description = "GPU-based texture tomography reconstruction framework"
readme = "README.md"
requires-python = ">=3.11"
authors = [
  { name = "Martin Sæbye Carøe" }
]
license = {text = "MIT"}

dependencies = [
  "numpy",
  "scipy",
  "pyopencl",
  "ase",
  "pymatgen",
  "gratopy",
  "pyclblast"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
diffractom = ["**/*.cl"]
